### ISSUE TITLE
Good first issue

### ISSUE THREAD

**Issue by dsasaank-369** [dsasaank-369/Pokemon#2]
Add a Pokemon card, you can find the steps to add in the Readme section. 

Happy Learning :)

**Comment by RohanHBTU** [comment]
May I work on this issue? I have experience with web development(HTML, CSS).

**Comment by Aman0307** [comment]
@dsasaank-369  I would like to contribute to this issue

**Comment by dpavan369** [comment]
@dsasaank-369 I want to Contribute to this issue

**Comment by sivanandula** [comment]
@dsasaank-369 I would like to contribute to this issue.

**Comment by dsasaank-369** [comment]
No need to wait for assigning, you can raise the pull request after adding the card.
Thank you.

**Comment by RohanHBTU** [comment]
The Spelling of Hactoberfest in the label of this repository is wrong. As a result, This repository is not being counted in Hactoberfest 2022.
Please correct the spelling soon.

**Comment by valak-69** [comment]
@dsasaank-369 i'd like to work on this issue and also wanted to know like the card template should be inserted in the html or do we need to do something else

**Comment by harshlokhande24** [comment]
Added Snorlax Card with image and color #27

**Comment by SKSilentKiller** [comment]
@dsasaank-369 Can you please assign me this

**Comment by maitreypatadia** [comment]
Hello, I want to contribute to this issue. Can you assign this task to me?

**Comment by Vivek-raj-64** [comment]
@dsasaank-369 I would like to contribute in this issue. Please assign it to me under hacktoberfest label.

**Comment by gitamandeep** [comment]
Sir, please  assign this issue to me . I would like to work on this issue

**Comment by RachitGarg-12** [comment]
I wanted to know will our PR on this be counted in hacktoberfest?

**Comment by Yashpsct010** [comment]
i would like to contribute in this issue
