### ISSUE TITLE
The Spelling of Hactoberfest in the label of this repository is wrong. As a result, This repository is not being counted in Hactoberfest 2022.

### ISSUE THREAD

**Issue by Satyabrat-Ojha** [dsasaank-369/Pokemon#45]
The Spelling of Hactoberfest in the label of this repository is wrong. As a result, This repository is not being counted in Hactoberfest 2022.
Please correct the spelling soon.

_Originally posted by @RohanHBTU in https://github.com/dsasaank-369/Pokemon/issues/2#issuecomment-1264023037_

**Comment by dsasaank-369** [comment]
Please check it, I have changed it already and the correct spelling is HACKTOBERFEST
